#!/usr/bin/env bash
# --- Global Git Post-Commit Hooks ---
for f in ~/.common/*.sh; do [ -f "$f" ] && . "$f"; done

printf "${CYAN}%s <%s>${NC}\n" "$(git config user.name)" "$(git config user.email)"
